# In this script we analyze the results from the EA runs
# which are saved in the file called:
# data/demographic_inference/ea_log_sfs.csv
# generated by the script:
# src/demographic_inference/print_csv_from_log_dir.py

# libraries:
library(tidyverse)
library(FactoMineR)

# read the data setting columns 2 to 8 as float and the 
# rest as string
df <- read.table("data/demographic_inference/ea_log_sfs.csv", 
                 sep = ",", 
                 header = T, 
                 colClasses = c(
                   rep("character", 1),
                   rep("numeric", 8),
                   rep("character", 1)
                   )
                 )

# remove rows with NAs
df <- df %>% drop_na()

# scale the values of columns 2 to 8 to be between 0 and 1 with
# 0 being the minimum and 1 being the maximum across all columns
df[,2:8] <- apply(df[,2:8], 2, function(x) (x - min(x)) / (max(x) - min(x)))

# run pca for columns 2 to 8
all_pca <- FactoMineR::PCA(df[,2:8], scale.unit = T, graph = F)
pca_df <- as.data.frame(all_pca$ind$coord)

# run pca for columns 2, 3, 5, 6, 7, 8
all_pca <- FactoMineR::PCA(df[,c(2,3,5,6,7,8)], scale.unit = T, graph = F)
pca_df <- as.data.frame(pca$ind$coord)

# add run type and fitness to the pca_df
pca_df$type <- df$type
pca_df$fitness <- df$fitness

# change fitness to a categorical variable where:
# - values between 0 and 4 are "low"
# - values between 4 and 8 are "medium"
# - values above 8 are"high"
pca_df$fitness <- ifelse(pca_df$fitness < 4, "low", 
                         ifelse(pca_df$fitness < 8, "medium", "high"))


# plot the pca:
# - scaling the points color by fitness (red = low, orange = medium, blue = high)
# - having a different shape for each run type
# - adding a legend at the bottom
# - adding amount of variance explained to the axis labels
ggplot(pca_df, aes(x = Dim.1, y = Dim.2, fill = fitness, shape = type)) +
  geom_point(size = 3) +
  scale_fill_manual(values = c("red", "orange", "blue")) +
  scale_shape_manual(values = c(22, 21)) +
  theme(legend.position = "bottom") +
  labs(x = paste0("Dim.1 (", round(all_pca$eig[1,2], 2), "%)"), 
       y = paste0("Dim.2 (", round(all_pca$eig[2,2], 2), "%)")) +
  theme_bw()

